version: 2.1

orbs:
  docker: circleci/docker@1.5.0

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: docker.io/mayank3107/aos/backend
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  publishLatestToHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - publishLatestToHub
