version: 2.1

orbs:
  docker: circleci/docker@1.5.0

executors:
  docker-publisher-node:
    environment:
      IMAGE_NAME: docker.io/mayank3107/aos
      IMAGE_TAG: frontend
    docker:
      - image: cimg/node:18.16
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

  docker-publisher-python:
    environment:
      IMAGE_NAME: docker.io/mayank3107/aos
      IMAGE_TAG: backend
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  publish-frontend:
    executor: docker-publisher-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Frontend Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            cd frontend
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker push $IMAGE_NAME:$IMAGE_TAG

  publish-backend:
    executor: docker-publisher-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Backend Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            cd backend
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-and-push:
    jobs:
      - publish-backend
      - publish-frontend
